[package]
name = "fldt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
any_vec = "0.12.0"
clap = { version = "4.3.21", features = ["derive"] }
rand = "0.8.5"
